[parity]
base_path = "db.tobalaba_ss_alice"
# chain = "tobalaba"
chain = "../chainspec/tobalaba.json"

[ui]
disable = false

[rpc]
disable = false
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts", "private", "secretstore"]
port = 8545
cors = ["*"]

[ipc]
disable = true

[dapps]
disable = false

[websockets]
disable = true

[ipfs]
enable = false

[network]
port = 30303
node_key = "af198921d2fd9c4f0a294a774f7a2aea9aae0631"
reserved_peers = "reserved_peers_alice.txt"

[snapshots]
disable_periodic = true

[secretstore]
disable = false
disable_http = false
acl_contract = "none"
#acl_contract = "ac33f781AA50052874EbbC85858a290Dc47C9aBC"
server_set_contract = "none"
#disable_acl_check = true
self_secret = "af198921d2fd9c4f0a294a774f7a2aea9aae0631"
interface = "all"
port = 8083
http_interface = "all"
http_port = 8090    
path = "db.tobalaba_ss_alice/secretstore"
nodes = [
    "df73521d73ba2014bfb1a40c7a582365da53ac093a82a72d7b9e26cdc5a339ef34137087030fd5dfab38d5e9515964def893548e8209f7861a6ff4f76f0e66f7@127.0.0.1:8083",
    "5ae2252871be8fb040c47308b895c68279ffe498b93dd601e6f7f1b4333f8218b60a600d25fe953b95c6962e71c3174d2c92d2774e4fcacc7d86739780280ebd@127.0.0.1:8085",
    "634c23892a957ef02a1952a65f2f1c89f5fffa28592068f4f31ec276981477ec86841d16a7fdf0c0836cf98ff24a1ba8dc546c95aeddde920a73f29cf2535d92@127.0.0.1:8087"
]

[misc]
logging = "transaction_pool=trace,txqueue=trace,ethcore_private_tx=trace,own_tx=trace"
log_file = "./db.tobalaba_ss_alice/parity.log"
color = true

[account] # unlock Alice's account to deploy the contract
unlock = ["0xaf198921d2fd9c4f0a294a774f7a2aea9aae0631"]
password = ["alice.pwd"]

[private_tx]
sstore_url = "http://127.0.0.1:8090"
enabled = true
account = "0xaf198921d2fd9c4f0a294a774f7a2aea9aae0631"
signer = "0xaf198921d2fd9c4f0a294a774f7a2aea9aae0631"
validators= ["0xaf198921d2fd9c4f0a294a774f7a2aea9aae0631"]
passwords = "alice.pwd"
